[colors]
draw_bold_text_with_bright_colors = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[general]
live_config_reload = true

[colors.bright]
black = "0x002b36"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0x6c71c4"
red = "0xdc322f"
white = "0xfdf6e3"
yellow = "0xb58900"

[colors.cursor]
cursor = "0x93a1a1"
text = "0x002b36"

[colors.normal]
black = "0x002b36"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0x6c71c4"
red = "0xdc322f"
white = "0x93a1a1"
yellow = "0xb58900"

[colors.primary]
background = "0x002b36"
foreground = "0x93a1a1"

[env]
TERM = "xterm-256color"

[font]
size = 18.0

#[font.bold]
#family = "JetBrainsMono Nerd Font"
#style = "Regular"

#[font.bold_italic]
#family = "JetBrainsMono Nerd Font"
#style = "Regular Italic"

#[font.italic]
#family = "JetBrainsMono Nerd Font"
#style = "Thin Italic"

#[font.normal]
#family = "JetBrainsMono Nerd Font"
#style = "Thin"

[font.bold]
family = "BlexMono Nerd Font"
style = "Regular"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Italic Regular"

[font.italic]
family = "BlexMono Nerd Font"
style = "Light Italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "Light"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_title = true
option_as_alt = "Both"
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 5
y = 22

[mouse]
